image: gitpod/workspace-postgres

ports:
  - name: Postgres Admin
    port: 8001
    onOpen: ignore
    visibility: private
  - name: Postgres
    port: 6379
    onOpen: ignore
    visibility: private
  - name: Redis
    port: 5432
    onOpen: ignore
  - name: Server
    port: 8000
    visibility: public
    onOpen: open-browser
  - name: GameServer
    port: 6000
    visibility: public
    onOpen: open-browser
  - name: React
    port: 3000
    visibility: public
    onOpen: open-browser

tasks:
  - name: Start Redis Stack
    init: |
     docker-compose pull
    command: |
     alias redis-cli="docker exec -it redis-stack redis-cli" 
     echo "Use redis-cli to interact with Redis here."
     docker-compose up -d
     gp sync-done finished
    openMode: tab-after
    
  - name: Start Postgres Stack
    init: |
     psql -h localhost -U gitpod -f sql/start.sql
    openMode: tab-after
    
  - name: Start GameFront Stack
    init: | 
     npm run install:game
    command: npm run dev:game
    openMode: tab-after

  - name: Start Server Stack
    init: | 
     npm run install:server
    command: npm run dev:server
    openMode: tab-after
    env:
      PORT: 8000
      POSTGRES: postgres://gitpod@localhost/alphagamesocket
      URL: gp url 8000
      SSL: false

  - name: Start GameServer Stack
    init: | 
     npm run install:gameserver
    command: npm run dev:gameserver
    openMode: tab-after
    env:
      PORT: 5000
      POSTGRES: postgres://gitpod@localhost/alphagamesocket
      URL: gp url 5000
      SSL: false

github: 
  prebuilds:
    master: true
    branches: true
    pullRequests: true