version: "3.9"
services:
  postgres:
      container_name: postgres-stack
      image: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgrespw
        - PGDATA=/data/postgres
      volumes: 
        - ./sql/constructor.sql:/docker-entrypoint-initdb.d/constructor.sql
        - db:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - postgres
      restart: unless-stopped

  redis:
    container_name: redis-stack
    image: redis
    ports:
      - "6379:6379"
      - "8001:8001"

  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server/security/:/ssl/
      - ./public/react/dist/:/etc/nginx/html    

networks:
  postgres:
    driver: bridge
  minha-rede:
    driver: bridge

volumes:
  db:
    driver: local
  sql: 