version: "3.9"
services:
  node:
      container_name: node-stack
      image: node/node-stack:latest
      ports:
        - "8000:8000"
        - "5000:5000"

  postgres:
      container_name: postgres-stack
      image: postgres/postgres-stack:latest

  redis:
    container_name: redis-stack
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"